### ISSUE TITLE
Minimum deployment target to iOS 9.0

### ISSUE THREAD

**Issue by blkshdw** [jerkoch/SwipeCellKit#1]
Hi.
Is it possible to lower the deployment target to iOS 9.0 ?

**Comment by jerkoch** [comment]
Hey @blkshdw - Unfortunately, this is not trivial since I'm using the new `UIViewPropertyAnimator ` which requires iOS 10 SDK.  

In your own fork, you could try rolling back to `UIView.animate`.  You'll need to figure out the equivalent spring animation parameters since `UIViewPropertyAnimator` makes this really simple, but it should be doable. Good luck!

**Comment by Codeido** [comment]
+1 for this improvements

**Comment by futuretap** [comment]
+1 from me, too
