### ISSUE TITLE
Request: Additional Expansion Style

### ISSUE THREAD

**Issue by Awalz** [jerkoch/SwipeCellKit#14]
I would love for there to be another expansion style. Similar to the Destructive style where the entire cell expands, but without the destructive properties. It would be useful for single, left side actions to transition to a new view controller or detail view.

Please let me know if this is possible with the existing expansion styles and I am missing something.
Thanks

Andrew

**Comment by jerkoch** [comment]
Hey @Awalz - This could probably be handled by a new flag in`SwipeAction` that disables SwipeCellKit from performing the table view row delete. Though, I'm not sure what would happen in the space where the cell used to be if its no longer gets deleted. For example, if this new VC/detail view doesn't cover the whole screen, etc.

Can you point me to any apps with a similar UX pattern so I can see an example?

**Comment by sgruby** [comment]
Hi @jerkoch, I have a client that wants to be able to swipe from the left and instead of tapping on the action, keep swiping and have the action triggered; this isn't a cell delete, just perform the action like your read/unread, but allow swiping all the way. MGSwipeTableCell has some called MGSwipeExpansionSettings which lets you specify that if the swipe has reached a certain amount of the way, expand all the way and take that action.

While this may not be a standard UX pattern, I have a client that wants it.

If you could consider it, I'd appreciate it.

**Comment by Alex293** [comment]
Would definitely be interested by this feature. A nice example for this would be in a task app, to complete a item just swipe left to right, for customisation swift right to left.

**Comment by jerkoch** [comment]
@sgruby @Alex293 I hear you  👍

I've been thinking about how to best make this happen. I've got an idea that I'll play around with tomorrow. Stay tuned!

**Comment by dginsburg** [comment]
> Can you point me to any apps with a similar UX pattern so I can see an example?

Tweetbot is a good example.

**Comment by jerkoch** [comment]
@Awalz @sgruby @Alex293

I added a `.fill` style expansion to the API.  Please see the discussion in #20 for more details.  If you choose to use the `.fill` style, it uses manual fulfillment, which means you need to call `action.fulfill(style:)` from inside your action handler. You can specify the fulfillment style as etiher `.delete` or `.reset` depending on the result of your modal user interaction.

Please take a look at the [expansion](/jerkoch/SwipeCellKit/tree/expansion) branch and let me know what you think!
