### ISSUE TITLE
Swiping left while holding down to select cell causes issue

### ISSUE THREAD

**Issue by seenoevo** [jerkoch/SwipeCellKit#26]
Currently, if I have the cell's `Selection` set to `Default`, and I press and hold down on the cell to select it, then perform a left swipe to reveal the SwipeAction buttons, the selected cell's background color is stuck on gray, and all the cell's properties (UILabel, etc.) that was set in the code defaults to the value set in StoryBoard.

I think it's a bug possibly?

@jerkoch you can test it out with the sample project

[Test.zip](https://github.com/jerkoch/SwipeCellKit/files/888254/Test.zip)

**Comment by jerkoch** [comment]
Hey @seenoevo, thanks for including a sample project.  👍

This issue is you're dequeuing a new cell in `func tableView(_ tableView: UITableView, editActionsForRowAt indexPath: IndexPath, for orientation: SwipeActionsOrientation) -> [SwipeAction]?`.  This delegate callback is only for returning swipe actions. 

You should only dequeue cells in `func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell`

**Comment by seenoevo** [comment]
doh!

tested and confirmed working now, thanks @jerkoch
