### ISSUE TITLE
Tableview dont trigger touch event

### ISSUE THREAD

**Issue by baschte** [jerkoch/SwipeCellKit#3]
First i want to say, that this Extension is awesome!! Im a beginner and love to work with it!! :-)

But i think i found a bug. If i run the example Mail App and swipe fast to delete a entry (Destructive) right after the entry disappeared i want to scroll the tableview but it doesn't trigger. Only if i tab on a Entry and go back everythink works fine again.

Can someone confirm it?
Include SwipeCellKit to my Project and get the same problem.

**Comment by jerkoch** [comment]
Thanks @baschte - Never noticed this before,  but it looks like a bug.  I'll take a closer look this afternoon.

**Comment by baschte** [comment]
@jerkoch can you tag the Extension to 1.2.1 pls? :-)
Thank you for fast fixing!!

**Comment by jerkoch** [comment]
Hey @baschte - Can you try the latest off develop before I cut a release?  Looks good on my end now.

**Comment by baschte** [comment]
@jerkoch sure ill give it a try now. wait a minute

**Comment by baschte** [comment]
@jerkoch works like a charme! Thank you!!

**Comment by jerkoch** [comment]
👍

1.2.1 is pushed!

**Comment by baschte** [comment]
hey @jerkoch is there any possibility to change the size of the ActionOption Button label or the button itself? need a hint :-)

thank you!

**Comment by jerkoch** [comment]
Hey @baschte - All the action button customization options are in `SwipeAction`.  You can set a custom font via the `font` property.  The button will try to use the minimum width depending on the text. Does that help?

**Comment by baschte** [comment]
@jerkoch yes i got that already but when i use a long word the text will break. Or if i change the text of a button dynamicly or if i make the fontsize bigger or something like that. It would be nice if i could set a label width or a button width for any SwipeAction. Is that possible or do you think someone else would need behaviours like that?

**Comment by jerkoch** [comment]
Hey @baschte - The border transition is based on all the buttons in an action menu being the same size (since they grow together from the edge). Design-wise, I'm not a big fan of when the buttons are different sizes like the built-in table view edit actions.  

Off the top of my head, we could possibly add a `buttonWidth` property on `SwipeOptions` that would apply uniformly to all the buttons in the active swipe menu - overriding the automatic sizing.  Thoughts?  

Can you open a new issue as an enhancement?  We can continue over there and get a better sense if this would be useful to other.
